---
title: "Questão 4"
output:
  html_document:
    df_print: paged
---

### Imports

```{r message=FALSE, warning=FALSE}
library(tidyverse)
source("./multiplot.R")
```


```{r message=FALSE, warning=FALSE}

# clean dataset from lizawood's github
url <- "https://raw.githubusercontent.com/lizawood/apps-and-games/master/PC_Games/PCgames_2004_2018_raw.csv"

# read in raw data
raw_df <- url %>% 
  read_csv() %>% 
  janitor::clean_names() 

# clean up some of the factors and playtime data
game_data <- raw_df %>% 
  mutate(price = as.numeric(price),
         score_rank = word(score_rank_userscore_metascore, 1),
         average_playtime = word(playtime_median, 1),
         median_playtime = word(playtime_median, 2),
         median_playtime = str_remove(median_playtime, "\\("),
         median_playtime = str_remove(median_playtime, "\\)"),
         average_playtime = 60 * as.numeric(str_sub(average_playtime, 1, 2)) +
           as.numeric(str_sub(average_playtime, 4, 5)),
         median_playtime = 60 * as.numeric(str_sub(median_playtime, 1, 2)) +
           as.numeric(str_sub(median_playtime, 4, 5)),
         metascore = as.double(str_sub(score_rank_userscore_metascore, start = -4, end = -3))) %>% 
  select(-score_rank_userscore_metascore, -score_rank, -playtime_median) %>% 
  rename(publisher = publisher_s, developer = developer_s)

```


```{r}
game_data$release_date <- str_sub(game_data$release_date, start = -4)

game_df <- game_data %>% 
  select(c("release_date", "price", "average_playtime")) %>% 
  group_by(release_date) %>% 
  summarise(price = mean(price, na.rm = TRUE), average_playtime = mean(average_playtime, na.rm = TRUE)) %>%
  ungroup() %>% 
  as.data.frame()

```

```{r}
game_df$release_date <- as.numeric(game_df$release_date, "%Y")

p <- game_df %>%
  ggplot(aes(x = release_date, y = average_playtime)) +
  geom_line()
  
p1 <- game_df %>%
    ggplot(aes(x = release_date, y = price)) +
    geom_line()

multiplot(p, p1)
```

